[package]
name = "gql"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
glob = "0.3.3"
libgql = { path = "./libgql" }
serde = "1.0.228"
serde_json = "1.0.148"
