name: "rust-gqlcodegen"

on:
  push:
    paths:
      - rust/gqlcodegen/**
      - .github/workflows/rust-gqlcodegen.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v5
      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        working-directory: rust/gqlcodegen
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}
      - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
        working-directory: rust/gqlcodegen
        run: cargo test --profile ${{ matrix.BUILD_TARGET }}
